(lang dune 3.10)

(name day2_2025)

(generate_opam_files true)

(package
 (name day2_2025)
 (synopsis "Advent of Code 2025 Day 2")
 (description "Advent of Code 2025 Day 2")
 (depends ocaml base stdio aoc_utils))
